config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
    get 'areas/index'
    resources :areas
    root 'areas#index'
    
    get 'routes/index'
    resources :routes
   
    
    
    get '/login' => 'sessions#new'
    post '/login' => 'sessions#create'
    get '/logout' => 'sessions#destroy'
    
    post '/users' => 'users#create'
    
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/area.rb
class Area < ApplicationRecord
    has_many :routes, :dependent => :restrict_with_error
    accepts_nested_attributes_for :routes, allow_destroy: true
end

app/models/route.rb
class Route < ApplicationRecord
    belongs_to :area
end

app/models/user.rb
class User < ApplicationRecord
    has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    
    def current_user
        @current_user ||= User.find(session[:user_id]) if session[:user_id]
    end
     helper_method :current_user
    
    def authorize
        redirect_to '/login' unless current_user
    end    
    
    
end

app/controllers/areas_controller.rb
class AreasController < ApplicationController
    
   before_action :authorize
    
    def index
        @areas = Area.all
    end   
    
    def show
        @area = Area.find(params[:id])
    end
    
    def new
        @area = Area.new
    end
    
    def create
        @area = Area.new(area_params)
        if @area.save
            redirect_to areas_path
        else
            render 'New'
        end
    end
    
    def edit
        @area = Area.find(params[:id])
    end
    
    def update
        @area = Area.find(params[:id])
        if @area.update_attributes(area_params)
            redirect_to areas_path
        else 
            render 'edit'
        end
    end
    
    def destroy
        @area = Area.find(params[:id])
        @area.destroy
        redirect_to areas_path
    end
    
    
    private
    
    def area_params
        params.require(:area).permit(:location, :latitude, :longtitude)
    end
    
    
    
    
end

app/controllers/routes_controller.rb
class RoutesController < ApplicationController
    before_action :authorize
    
    
    
    
    def index

        @routes = Route.all
        
    end
    
    def show
        @route = Route.find(params[:id])
    end
    
    
    def new
        @route = Route.new
    end
    
    def create 
        @area = Area.find(route_params[:area_id])
        @route = @area.routes.new(route_params)
        if @route.save
            redirect_to routes_path
        else 
            render 'new'
        end    
    end
    
    def edit
        @route = Route.find(params[:id])
    end
    
    def update
        @route = Route.find(params[:id])
        if @route.update_attributes(route_params)
            redirect_to routes_path
        else
            render 'edit'
        end
    end
    
    def destroy
        @route = Route.find(params[:id])
        @route.destroy
        redirect_to routes_path
    end
    
    private
    def route_params
        params.require(:route).permit(:start_point, :destination, :distance)
    end    
    
    
    
    
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    
    def new
    end
    
    def create
        user = User.find_by_username(params[:username])
        if user && user.authenticate(params[:password])
            session[:user_id] = user.id
            redirect_to '/'
        else
            redirect_to '/login'
        end
    end
    
    def destroy
        session[:user_id] = nil
        redirect_to '/login'
    end    
    
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    
    def new
        
    end 
    
    def create
        @user = User.new(user_params)
        if @user.save
            session[:user_id] = @user.id
            redirect_to '/'
        else
            render '/signup'
        end
    end
    
    
    private
    def user_params
        params.require(:user).permit(:username, :password, :password_confirmation)
    end    
    
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/areas_helper.rb
module AreasHelper
end

app/helpers/routes_helper.rb
module RoutesHelper

end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/areas/_form.html.erb
<div align= "center">
    <%= form_with model: @area, local: true do |form| %>
        <div class="field">
            <%= form.label :location %><br>
            <%= form.text_field :location %>
        </div>

        <div class="field">
            <%= form.label :longtitude %>
            <%= form.text_field :longtitude %>
        </div>

        <div class="field">
            <%= form.label :latitude %>
            <%= form.text_field :latitude %>
        </div>

        <div>
            <%= form.submit %>
        </div>

    <% end %>
</div>    

app/views/areas/edit.html.erb
<div class= "center jumbotron">
    <h1>Edit Store</h1>
    <%= form_with model: @area, local: true do |form| %>
        <div class="field">
            <%= form.label :location %><br>
            <%= form.text_field :location %>
        </div>

        <div class="field">
            <%= form.label :longtitude %><br>
            <%= form.text_field :longtitude %>
        </div>
    
        <div class="field">
            <%= form.label :latitude %><br>
            <%= form.text_field :latitude %>
        </div>

        <div>
            <%= form.submit %>
        </div>
    <% end %>
    
</div>

app/views/areas/index.html.erb
<div align= "center">
        <h1>Areas</h1>

        <table class="row-border" frame="void" rules="rows" cellspacing="10">
            <tr>
                <th colspan=5>Location</th>
            </tr>

            <% @areas.each do |area| %>
                <tr>
                    <td>
                        <%= area.location %>  <%= area.latitude %>  <%= area.longtitude %>
                    </td>
                    
                    <td><%= link_to edit_area_path([:id]), class: "btn btn-default" do %>
                    <span class="glyphicon glyphicon-pencil" aria-hidden="true"></span> <% end %>
                    </td>
                    
                    <td><%= link_to area_path(area[:id]), class: "btn btn-default", method: :delete, data: {confirm: 'Are you sure'} do %>
                        <span class="glyphicon glyphicon-trash" aria-hidden="true"></span>
                        <% end %>
                    </td>    
                    
                </tr>
            <% end %>
            
        </table>
          
        

        <%= link_to 'Create', new_area_path , class: "btn btn-lg btn-primary" %> 
    
</div>


    <%= link_to 'Routes', routes_path %>

app/views/areas/new.html.erb
    <h1>New area</h1>
    <%= render 'form' %>
    <%= link_to 'Back', areas_path, class: "btn btn-lg btn-primary" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>HackathonBackend</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
       <nav class="navbar navbar-inverse navbar-fixed-top bg-inverse", style="margin-bottom: 0px;">
            <div class="container">  
              
                <a class="navbar-brand" >Areas Routes</a>
            </div>
             
            <div class="center jumbotron">  
                   
                <% if current_user %>
                  Signed in as <%= current_user.username %> | <%= link_to "Logout", '/logout' %> 
                <% else %>
                  
                <% end %>  

                <%= yield %>
           </div>
      </nav>   
  </body>
</html>

app/views/routes/_form.html.erb
<%= simple_form_for @route do |f| %>
    <%= f.input :area, location: 'Serres' %>
        <div class="form-group">
            <%= f.label :area %>
            <div class="field">
                <%= f.area_select(:area_id, Area.all, :id, :location) %>
            </div>

        </div>
        <%= f.button :submit %>
<% end %>

app/views/routes/edit.html.erb
<div class= "center jumbotron">
    <h1>Edit Store</h1>
    <%= form_with model: @route, local: true do |form| %>
        

        <div class="field">
            <%= form.label :distance %>
            <%= form.text_field :distance %>
        </div>

        <div>
            <%= form.submit %>
        </div>

    <% end %>
    
</div>    

app/views/routes/new.html.erb
    <h1>New Route</h1>
    <%= render 'form' %>
    <%= link_to 'Back', routes_path, class: "btn btn-lg btn-primary" %>